### ISSUE TITLE
sync can fail if dowstream job triggers and finishes rebuild

### ISSUE THREAD

**Issue by tfoote** [ros-infrastructure/buildfarm#121]
When the sync is running if a package underneath finishes building it will abort.  

This is an issue in that if the new package is low level it will not sync until everything is rebuilt leaving shadow-fixed empty.  

We just need to make sure that the sync holds the uploading lock so other uploads will be blocked while the sync is in progress.

**Comment by dirk-thomas** [comment]
Both job types run on a single slave on the new buildfarm and therefore prevent this.

Won't be addressed for the existing farm.
