### ISSUE TITLE
Jenkins job on `64.91.234.231_sync` does not finish in 120 minutes

### ISSUE THREAD

**Issue by garaemon** [ros-infrastructure/buildfarm#220]
Is there any difference in computation power between 69.16.195.238 and 64.91.234.231_sync?

Job using 64.91.234.231_sync does not finish [log](http://jenkins.ros.org/view/IbinS64/job/ros-indigo-jsk-pcl-ros_binarydeb_saucy_amd64/98/consoleFull) but job on 69.16.195.238  finishes in 120 minutes [log](http://jenkins.ros.org/view/IbinS64/job/ros-indigo-jsk-pcl-ros_binarydeb_saucy_amd64/101/consoleFull)

**Comment by tfoote** [comment]
They are the same machine. The sync one is slightly older and is special in that it is the only one allowed to run sync jobs. There's always going to be some variability on the build time. This package is very clearly near the edge. Things that can effect the built time are other hosts on the VM, bandwidth available, and how much overlap is in the caches from recent builds.

**Comment by garaemon** [comment]
I see. I will decrease time to build the package. thanks

**Comment by tfoote** [comment]
Thanks, keeping the build timeouts down keeps the whole system turning over quicker.
