### ISSUE TITLE
QEMU issue (when building for ARM)

### ISSUE THREAD

**Issue by po1** [ros-infrastructure/buildfarm#87]
As stated here:
https://bugs.launchpad.net/qemu/+bug/955379

there is big problem with all current versions of qemu, which (among other) can be triggered by cmake.
What happens is that sometimes, during a check (for CXX ABI info among others), the whole build process hangs forever. It hangs because there is a bug in the select() call handler in QEMU, and that the SIGCHLD is lost in space when the child finishes, for which the parent (cmake) waits forever and ever.

Quick workaround: when that happens, manually doing a 'kill -SIGCHLD $pid' will unlock the cmake process and resume its execution.
As I see it, there are 2 things we can do:
1. write a script that automates the SIGCHLD sending when the build process hangs
2. write a patch for qemu

No. 2 does not sound very realistic...

**Comment by dirk-thomas** [comment]
The existing buildfarm will not be modified anymore. If this is this a problem on the new farm please consider filling a new ticket there (related to https://github.com/ros-infrastructure/ros_buildfarm/issues/21).
